Music player
tmaciulis22/Moodis pull request #17
Opened 2019-10-09 07:37 UTC by pagiriotas

2019-10-09 07:40 UTC, pagiriotas commented on Moodis/Moodis/Feature/MP3Player/MusicPlayer.cs
> +
empty line

2019-10-09 07:40 UTC, pagiriotas commented on Moodis/Moodis/Feature/MP3Player/MusicPlayer.cs
> +
empty line

2019-10-09 07:40 UTC, pagiriotas commented on Moodis/Moodis/Feature/MP3Player/MusicPlayerModel.cs
> +
empty line

2019-10-09 14:21 UTC, Pilkas-git requested changes
Great just a few small fixes needed .

2019-10-09 14:21 UTC, Pilkas-git commented on Moodis/Moodis/Feature/MP3Player/MusicPlayerModel.cs
> +
Empty line :-)

2019-10-09 14:21 UTC, Pilkas-git commented on Moodis/Moodis/Feature/Menu/MenuForm.cs
EmPtY LiNe

2019-10-09 14:21 UTC, Pilkas-git commented on Moodis/Moodis/Feature/Menu/MenuForm.cs
> +            foreach (var label in menuViewModel.currentImage.emotions)
rename label to something more meaningfull, i though you began to take info from lbl.Text.

2019-10-09 15:29 UTC, Pilkas-git approved these changes

2019-10-10 14:12 UTC, tmaciulis22 requested changes
One change

2019-10-10 14:12 UTC, tmaciulis22 commented on Moodis/Moodis/Feature/Menu/MenuForm.cs
> +            player.StartMusic(index);
You can use this stack overflow answer to change this whole block of finding highest emotion to just few lines:
https://stackoverflow.com/a/13755053

2019-10-10 14:28 UTC, pagiriotas commented on Moodis/Moodis/Feature/Menu/MenuForm.cs
> +            player.StartMusic(index);
I don't believe that this would be better. Since this is array of struct, we cannot access max from it. We would need to create new List or an Array to add confidence values and then use additional library to do the same job.

2019-10-10 14:48 UTC, tmaciulis22 commented on Moodis/Moodis/Feature/Menu/MenuForm.cs
> +            player.StartMusic(index);
Then implement IComparable for Emotion. This way we would complete one more requirement

2019-10-12 21:17 UTC, merged