Feature/music player
tmaciulis22/Moodis pull request #34
Opened 2019-11-04 11:13 UTC by Pilkas-git

Initial Music player feature. Works as it worked in windows forms. Also has a feature to take songs from web urls (will be needed as spotify provides song preview url). For spotify integration we still need to redesign the main menu window to support some kind of options or side pannel, because floading the user with buttons won't do any good.

2019-11-07 14:11 UTC, tmaciulis22 requested changes
Resolve conflicts

2019-11-11 15:46 UTC, tmaciulis22 requested changes
🔍

2019-11-11 15:46 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/CameraFeature/CameraActivity.cs
> +                .CommitAllowingStateLoss();
Why you changed from simple commit?

2019-11-11 15:46 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Resources/layout/activity_menu.xml
> +    android:id="@+id/menuActivity"
Put id attribute on the top, so xml file would be easier to read

2019-11-11 15:46 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Resources/values/strings.xml
> +  <string name="warning_in_request">Something wrong happened. Is your internet turned on?</string>
unused string

2019-11-11 18:37 UTC, Pilkas-git commented on app-android-xamarin/Moodis/Moodis/Feature/CameraFeature/CameraActivity.cs
> +                .CommitAllowingStateLoss();
was required while testing on emulator.

2019-11-11 18:56 UTC, tmaciulis22 approved these changes

2019-11-11 22:54 UTC, AArlauskas approved these changes
Maladecas esi kad tvarka kode palaikai

2019-11-13 17:43 UTC, Pilkas-git commented
how ?

2019-11-13 17:56 UTC, merged