Feature/calendar and statistics
tmaciulis22/Moodis pull request #35
Opened 2019-11-04 22:45 UTC by tmaciulis22

5 PRs in 1. Migrated not only statistics and calendar, but also face detection, sign and registration with face. TODO in next PR: add more charts and put emotion struct to DB.

2019-11-04 23:10 UTC, AArlauskas approved these changes
Too long didn't read

2019-11-04 23:10 UTC, pagiriotas commented on app-android-xamarin/Moodis/Moodis/Feature/Register/RegisterFaceActivity.cs
> +
is this an empty line 😮

2019-11-04 23:10 UTC, pagiriotas commented on app-android-xamarin/Moodis/Moodis/Feature/SignIn/SignInActivity.cs
> +        public static int REQUEST_CODE_FACE = 1;
A tu man kartais nepasakojai kad cia skaiciukas dva turetu buti?

2019-11-06 10:08 UTC, Pilkas-git requested changes

2019-11-06 10:08 UTC, Pilkas-git commented on app-android-xamarin/Moodis/Moodis/Network/Face/Face.cs
> +                Console.WriteLine(API_ERROR + " " + apiException.StackTrace);//TODO change to Log
change to log

2019-11-06 10:08 UTC, Pilkas-git commented on app-android-xamarin/Moodis/Moodis/Models/ImageInfo.cs
> +        public List<Emotion> emotions;
Just a question, does the db not support structs ?

2019-11-06 10:08 UTC, Pilkas-git commented on app-android-xamarin/Moodis/Moodis/Feature/CameraFeature/CameraFragment.cs
> +        public override async void OnViewCreated(View view, Bundle savedInstanceState)
Don't think this needs async as you only await on line 65 which is already handled by AfterTakenPicture = async (sender, e) =>

2019-11-06 11:36 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Models/ImageInfo.cs
> +        public List<Emotion> emotions;
Will solve this issue in next PR

2019-11-06 22:11 UTC, Pilkas-git approved these changes
Leave some work for the rest of us :DD

2019-11-06 22:11 UTC, merged