Rožos aptiktuolio pakeitimai
tmaciulis22/Moodis pull request #37
Opened 2019-11-11 22:49 UTC by pagiriotas

Darau PR ne del to kad noriu o del to kad reikia. Atsiras laiko, gal ir noras sugris

2019-11-11 22:56 UTC, pagiriotas commented
https://www.youtube.com/watch?v=Q55Ic4Mpdlk

2019-11-28 21:34 UTC, tmaciulis22 requested changes
Is login with credentials still working? Beisdes, there are some conflicts

2019-11-28 21:34 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/MainActivity.cs
> +
nice

2019-11-28 22:23 UTC, pagiriotas commented on app-android-xamarin/Moodis/Moodis/Feature/MainActivity.cs
> +
Why shouldn't it be?

2020-02-03 15:19 UTC, closed without merging