Menu drawer
tmaciulis22/Moodis pull request #38
Opened 2019-11-17 11:15 UTC by Pilkas-git

Menu drawer implementation. Changes menu ui, to support more buttons/paths via drawer.

2019-11-17 15:42 UTC, tmaciulis22 requested changes
issues with activity back stack⚠

2019-11-17 15:42 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/Menu/MenuActivity.cs
> +
unnecessary empty line

2019-11-17 15:42 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/Menu/MenuActivity.cs
> +                StartActivity(new Intent(this, typeof(CameraActivity)));
You are doing the same mistake here regarding activity back stack. Just test it by yourself. Continously open menu activity, then click on camera in nav drawer, take picture, go to menu activity again. Do this repeatedly for a few times, then click back button repeatedly. You'll notice that you have not one, but many menu and camera activities opened.

2019-11-17 15:42 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/Menu/MenuActivity.cs
> +            if (id == Resource.Id.nav_camera)
maybe it would be nicer to change these if's to `switch` statement?

2019-11-17 15:42 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Resources/layout/activity_menu.xml
> +                                        xmlns:app="http://schemas.android.com/apk/res-auto"
bad alignment

2019-11-17 15:42 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Resources/layout/app_bar_main.xml
> +
unnecessary empty line

2019-11-17 16:52 UTC, tmaciulis22 requested changes

2019-11-17 16:52 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/Menu/MenuActivity.cs
>              Finish();
move 'Finish()` to `else` block

2019-11-17 16:52 UTC, tmaciulis22 commented on app-android-xamarin/Moodis/Moodis/Feature/Menu/MenuActivity.cs
>                      Finish();
Use `FinishAffinity()` here

2019-11-17 19:03 UTC, tmaciulis22 approved these changes
💜

2019-11-28 10:07 UTC, AArlauskas approved these changes

2019-11-28 10:08 UTC, merged