Connecting app to be
tmaciulis22/Moodis pull request #47
Opened 2019-12-08 14:23 UTC by tmaciulis22

All functionality is connected to BE, except for doctor's app.

One bug is still left unfixed. You cannot for some reason sign in with credentials, except when you register a user through Postman. Andrius will try to fix it.

Besides, I made regex a bit easier and some additional UI changes

2019-12-08 20:46 UTC, Pilkas-git requested changes
nice work. Small naming changes left . :+1:

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var entity = dbContext.Groups.Single(g => g.Id == id);
Change naming of g to group.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var groups = dbContext.Groups.TakeWhile(e => e.DoctorId == doctorId).Select(group => new GroupFE()
sane here

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Include(item => item.ImageInfos).Single(u => u.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Include(item => item.ImageInfos).Single(u => u.PersonId == personId);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/ImageInfoController.cs
> +                    var entity = dbContext.ImageInfos.Single(e => e.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/ImageInfoController.cs
> +                    var entity = dbContext.Groups.Single(e => e.Id == id);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var isAlreadyRegistered = dbContext.Users.Any(u => u.Username == request.Username);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Single(e => e.Id == user.Id);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Single(e => e.Id == id);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var entity = dbContext.Groups.Single(g => g.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var groups = dbContext.Groups.TakeWhile(e => e.DoctorId == doctorId).Select(group => new GroupFE()
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var entity = dbContext.Groups.Single(e => e.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/GroupController.cs
> +                    var entity = dbContext.Groups.Single(e => e.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/ImageInfoController.cs
> +                    var entities = dbContext.ImageInfos.AsEnumerable().SkipWhile(e => e.UserId != userId);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/ImageInfoController.cs
> +                    var entity = dbContext.ImageInfos.Single(e => e.Id == id);
naming

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/ImageInfoController.cs
> +                    var entity = dbContext.Groups.Single(e => e.Id == id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Single(e => e.Id == user.Id);
naming.

2019-12-08 20:46 UTC, Pilkas-git commented on API/MoodisAPI/apiMoodis/apiMoodis/Controllers/UserController.cs
> +                    var entity = dbContext.Users.Single(e => e.Id == id);
naming.

2019-12-08 21:06 UTC, Pilkas-git approved these changes
👍👍👍👍👍👍👍👍👍

2019-12-09 00:54 UTC, AArlauskas approved these changes
That's big. Really big. Like really fucking big. Good job, Tautvydas. Good job.

2019-12-09 07:09 UTC, merged